alertmanager:
  persistentVolume:
    enabled: false

server:
  fullnameOverride: prometheus-server
  persistentVolume:
    enabled: false

extraScrapeConfigs: |
    - job_name: karpenter
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          -
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_endpoints_name
        - __meta_kubernetes_endpoint_port_name
        action: keep
        regex: karpenter;http-metrics

################################################
# You want Prometheus metrics not to be lost on pod restart. Use gp3 (better than gp2, cheaper, faster).
#################################################

alertmanager:
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: gp3

server:
  fullnameOverride: prometheus-server
  persistentVolume:
    enabled: true
    size: 50Gi
    storageClass: gp3

extraScrapeConfigs: |
  - job_name: karpenter
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - default
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_endpoints_name
      - __meta_kubernetes_endpoint_port_name
      action: keep
      regex: karpenter;http-metrics

# This creates: 10Gi PVC for Alertmanager, 50Gi PVC for Prometheus server. Each backed by EBS volumes provisioned via CSI driver.

