---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: 6-example
spec:
  type: ClusterIP # not LoadBalancer in this case for AWS ALB
  ports:
    - port: 8080
      targetPort: http
  selector:
    app: myapp
